### ISSUE TITLE
Current window is change if one buffer opened in multi windows

### ISSUE THREAD

**Issue by rapan931** [skanehira/translate.vim#5]
## reproduced
```
"Lunch
gvim.exe -Nu NONE

" Setting
:set rtp+=/path/to/translate.vim
:runtime plugin/translate.vim
:let g:translate_source = 'ja'
:let g:translate_target = 'en'

" One buffer opend 2 window
i俺は海賊王になる<ESC><C-w>v

" Move right window
<C-w>l

" Select string and do :Translate
_vg_:Translate
```

expected: not move current window
actuary: move current window

## version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 16 2019 22:08:59)
MS-Windows 64 ビット GUI 版 with OLE サポート
適用済パッチ: 1-1866

Windows7

## other
すみません、日本語で、、
複数Windowで同じバッファを開いている状態で:Translateを実施すると
一番左のウィンドウ がカレントウィンドウになっているようです。

ご確認宜しくお願いします。:bow:

**Comment by skanehira** [comment]
@rapan931 f9519eb で修正しました
更新して試してみてください

**Comment by rapan931** [comment]
最新バージョンで修正されていること確認できました。
対応ありがとうございました！
