### ISSUE TITLE
AutoTranslateMode is not working

### ISSUE THREAD

**Issue by siaa4fu** [skanehira/translate.vim#8]
`:AutoTranslateModeEnable` した際にうまく動かなかったので報告です。

`s:focus_window()` が window-ID を要求していますが、違ったものを渡しているためにウィンドウフォーカスの処理でおかしくなっているように思いました。

以下の部分をそれぞれ修整すると良さそうです。

https://github.com/skanehira/translate.vim/blob/97f97c5e3413b2747fe1e1b270c5f1bf6e8bcdad/autoload/translate.vim#L130
```vim
let s:currentw = win_getid()
```

https://github.com/skanehira/translate.vim/blob/97f97c5e3413b2747fe1e1b270c5f1bf6e8bcdad/autoload/translate.vim#L173
```vim
call s:focus_window(bufwinid(tranw))
```

素敵なプラグインをありがとうございます :smile:

**Comment by skanehira** [comment]
@sima-fu ありがとうございます！
ソース確認します！

**Comment by skanehira** [comment]
@sima-fu 
v1をリリースしました
そこで、自動翻訳機能を廃止しました
シンプルな翻訳機能だけのプラグインにして、あとはユーザカスタマイズに任せたほうが良いと考えたためです

もし自動翻訳を使いたい場合はご自身でカスタマイズしていただくことになりますが、
引き続きご利用いただければと思います
